---
title: "Function: sequelize()"
description: "Function: sequelize() API reference from @automapper/sequelize."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/sequelize**](../index)

***



> **sequelize**(`options?`): `MappingStrategyInitializer`\<`MetadataIdentifier`\>

Defined in: [sequelize.ts:12](https://github.com/nartc/mapper/blob/main/packages/sequelize/src/lib/sequelize.ts#L12)

## Parameters

### options?

`MappingStrategyInitializerOptions` = `defaultStrategyInitializerOptions`

## Returns

`MappingStrategyInitializer`\<`MetadataIdentifier`\>
