---
title: "Variable: AUTOMAP\\_PROPERTIES\\_METADATA\\_KEY"
description: "Variable: AUTOMAP\\_PROPERTIES\\_METADATA\\_KEY API reference from @automapper/classes."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/classes**](../index)

***



> `const` **AUTOMAP\_PROPERTIES\_METADATA\_KEY**: `"automap:properties"` = `'automap:properties'`

Defined in: [keys.ts:3](https://github.com/nartc/mapper/blob/main/packages/classes/src/lib/keys.ts#L3)
