---
title: "Variable: AUTOMAPPER\\_METADATA\\_FACTORY\\_KEY"
description: "Variable: AUTOMAPPER\\_METADATA\\_FACTORY\\_KEY API reference from @automapper/classes."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/classes**](../index)

***



> `const` **AUTOMAPPER\_METADATA\_FACTORY\_KEY**: `"__AUTOMAPPER_METADATA_FACTORY__"` = `'__AUTOMAPPER_METADATA_FACTORY__'`

Defined in: [keys.ts:1](https://github.com/nartc/mapper/blob/main/packages/classes/src/lib/keys.ts#L1)
