---
title: "Variable: AUTOMAP\\_STANDALONE\\_METADATA\\_KEY"
description: "Variable: AUTOMAP\\_STANDALONE\\_METADATA\\_KEY API reference from @automapper/classes."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/classes**](../index)

***



> `const` **AUTOMAP\_STANDALONE\_METADATA\_KEY**: `"automap:standalone"` = `'automap:standalone'`

Defined in: [keys.ts:4](https://github.com/nartc/mapper/blob/main/packages/classes/src/lib/keys.ts#L4)
