---
title: "Type Alias: PojoMetadata"
description: "Type Alias: PojoMetadata API reference from @automapper/pojos."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/pojos**](../index)

***



> **PojoMetadata** = `Exclude`\<`ModelIdentifier`, `Constructor`\> \| `AnyConstructor`

Defined in: [metadata-map.ts:8](https://github.com/nartc/mapper/blob/main/packages/pojos/src/lib/metadata-map.ts#L8)
