---
title: "Function: beforeMap()"
description: "Function: beforeMap() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **beforeMap**\<`TSource`, `TDestination`\>(`cb`): [`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TDestination`\>

Defined in: [packages/core/src/lib/mapping-configurations/before-map.ts:4](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/mapping-configurations/before-map.ts#L4)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

## Parameters

### cb

[`MapCallback`](../type-aliases/MapCallback)\<`TSource`, `TDestination`\>

## Returns

[`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TDestination`\>
