---
title: "Function: constructUsing()"
description: "Function: constructUsing() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **constructUsing**\<`TSource`, `TDestination`\>(`destinationConstructor`): [`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TDestination`\>

Defined in: [packages/core/src/lib/mapping-configurations/construct-using.ts:9](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/mapping-configurations/construct-using.ts#L9)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

## Parameters

### destinationConstructor

[`DestinationConstructor`](../type-aliases/DestinationConstructor)\<`TSource`, `TDestination`\>

## Returns

[`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TDestination`\>
