---
title: "Function: createMapper()"
description: "Function: createMapper() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **createMapper**(`options`): [`Mapper`](../interfaces/Mapper)

Defined in: [packages/core/src/lib/core.ts:61](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/core.ts#L61)

Creates and returns a Mapper {}. The following methods are available to use with a Mapper:
 ```
 - Mapper#map(Array)(Async), Mapper#mutate(Array)(Async)
 - createMap()
 - addProfile()
 - getMapping()
 - getMappings()
 ```

## Parameters

### options

[`CreateMapperOptions`](../interfaces/CreateMapperOptions)

## Returns

[`Mapper`](../interfaces/Mapper)
