---
title: "Function: createMap()"
description: "Function: createMap() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



## Call Signature

> **createMap**\<`TSource`\>(`mapper`, `source`, ...`mappingConfigFns`): [`Mapping`](../type-aliases/Mapping)\<`TSource`, `TSource`\>

Defined in: [packages/core/src/lib/mappings/create-map.ts:20](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/mappings/create-map.ts#L20)

### Type Parameters

#### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

### Parameters

#### mapper

[`Mapper`](../interfaces/Mapper)

#### source

[`ModelIdentifier`](../type-aliases/ModelIdentifier)\<`TSource`\>

#### mappingConfigFns

...([`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TSource`\> \| `undefined`)[]

### Returns

[`Mapping`](../type-aliases/Mapping)\<`TSource`, `TSource`\>

## Call Signature

> **createMap**\<`TSource`, `TDestination`\>(`mapper`, `source`, `destination`, ...`mappingConfigFns`): [`Mapping`](../type-aliases/Mapping)\<`TSource`, `TDestination`\>

Defined in: [packages/core/src/lib/mappings/create-map.ts:25](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/mappings/create-map.ts#L25)

### Type Parameters

#### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

#### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

### Parameters

#### mapper

[`Mapper`](../interfaces/Mapper)

#### source

[`ModelIdentifier`](../type-aliases/ModelIdentifier)\<`TSource`\>

#### destination

[`ModelIdentifier`](../type-aliases/ModelIdentifier)\<`TDestination`\>

#### mappingConfigFns

...([`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TDestination`\> \| `undefined`)[]

### Returns

[`Mapping`](../type-aliases/Mapping)\<`TSource`, `TDestination`\>
