---
title: "Function: extend()"
description: "Function: extend() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



## Call Signature

> **extend**\<`TSource`, `TDestination`, `TExtendSource`, `TExtendDestination`\>(`mapping`): [`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TDestination`\>

Defined in: [packages/core/src/lib/mapping-configurations/extend.ts:12](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/mapping-configurations/extend.ts#L12)

### Type Parameters

#### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

#### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

#### TExtendSource

`TExtendSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TExtendSource`\>

#### TExtendDestination

`TExtendDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TExtendDestination`\>

### Parameters

#### mapping

[`Mapping`](../type-aliases/Mapping)\<`TExtendSource`, `TExtendDestination`\>

### Returns

[`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TDestination`\>

## Call Signature

> **extend**\<`TSource`, `TDestination`, `TExtendSource`, `TExtendDestination`\>(`source`, `destination`): [`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TDestination`\>

Defined in: [packages/core/src/lib/mapping-configurations/extend.ts:20](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/mapping-configurations/extend.ts#L20)

### Type Parameters

#### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

#### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

#### TExtendSource

`TExtendSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TExtendSource`\>

#### TExtendDestination

`TExtendDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TExtendDestination`\>

### Parameters

#### source

[`ModelIdentifier`](../type-aliases/ModelIdentifier)\<`TExtendSource`\>

#### destination

[`ModelIdentifier`](../type-aliases/ModelIdentifier)\<`TExtendDestination`\>

### Returns

[`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TDestination`\>
