---
title: "Function: forMember()"
description: "Function: forMember() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **forMember**\<`TSource`, `TDestination`, `TMemberType`\>(`selector`, ...`fns`): [`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TDestination`\>

Defined in: [packages/core/src/lib/mapping-configurations/for-member.ts:14](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/mapping-configurations/for-member.ts#L14)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

### TMemberType

`TMemberType` = `unknown`

## Parameters

### selector

[`Selector`](../type-aliases/Selector)\<`TDestination`, `TMemberType`\>

### fns

...\[[`PreConditionReturn`](../type-aliases/PreConditionReturn)\<`TSource`, `TDestination`, `TMemberType`\> \| [`MemberMapReturn`](../type-aliases/MemberMapReturn)\<`TSource`, `TDestination`, `TMemberType`\>, [`MemberMapReturn`](../type-aliases/MemberMapReturn)\<`TSource`, `TDestination`, `TMemberType`\>\]

## Returns

[`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TDestination`\>
