---
title: "Function: forSelf()"
description: "Function: forSelf() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **forSelf**\<`TSource`, `TDestination`, `TSelfSource`\>(`sourceOrMapping`, `selector`): [`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TDestination`\>

Defined in: [packages/core/src/lib/mapping-configurations/for-self.ts:23](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/mapping-configurations/for-self.ts#L23)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

### TSelfSource

`TSelfSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSelfSource`\>

## Parameters

### sourceOrMapping

[`ModelIdentifier`](../type-aliases/ModelIdentifier)\<`TSelfSource`\> \| [`Mapping`](../type-aliases/Mapping)\<`TSelfSource`, `TDestination`\>

### selector

[`Selector`](../type-aliases/Selector)\<`TSource`, `TSelfSource`\>

## Returns

[`MappingConfiguration`](../type-aliases/MappingConfiguration)\<`TSource`, `TDestination`\>
