---
title: "Function: ignore()"
description: "Function: ignore() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **ignore**\<`TSource`, `TDestination`\>(): [`IgnoreReturn`](../type-aliases/IgnoreReturn)\<`TSource`, `TDestination`\>

Defined in: [packages/core/src/lib/member-map-functions/ignore.ts:4](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/member-map-functions/ignore.ts#L4)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

## Returns

[`IgnoreReturn`](../type-aliases/IgnoreReturn)\<`TSource`, `TDestination`\>
