---
title: "Function: isDateConstructor()"
description: "Function: isDateConstructor() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **isDateConstructor**(`value`): `boolean`

Defined in: [packages/core/src/lib/utils/is-date-constructor.ts:6](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/utils/is-date-constructor.ts#L6)

Check if value is a Date constructor

## Parameters

### value

`unknown`

## Returns

`boolean`
