---
title: "Function: mapDefer()"
description: "Function: mapDefer() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **mapDefer**\<`TSource`, `TDestination`, `TSelectorReturn`\>(`defer`): [`MapDeferReturn`](../type-aliases/MapDeferReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\>

Defined in: [packages/core/src/lib/member-map-functions/map-defer.ts:4](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/member-map-functions/map-defer.ts#L4)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\> = `any`

### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\> = `any`

### TSelectorReturn

`TSelectorReturn` = `unknown`

## Parameters

### defer

[`DeferFunction`](../interfaces/DeferFunction)\<`TSource`, `TDestination`, `TSelectorReturn`\>

## Returns

[`MapDeferReturn`](../type-aliases/MapDeferReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\>
