---
title: "Function: mapWithArguments()"
description: "Function: mapWithArguments() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **mapWithArguments**\<`TSource`, `TDestination`, `TSelectorReturn`\>(`withArgumentsResolver`): [`MapWithArgumentsReturn`](../type-aliases/MapWithArgumentsReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\>

Defined in: [packages/core/src/lib/member-map-functions/map-with-arguments.ts:11](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/member-map-functions/map-with-arguments.ts#L11)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

### TSelectorReturn

`TSelectorReturn` = `unknown`

## Parameters

### withArgumentsResolver

[`Resolver`](../interfaces/Resolver)\<`TSource`, `Record`\<`string`, `unknown`\>, `TSelectorReturn`\> \| ((`source`, `extraArguments`) => [`MaybePromise`](../type-aliases/MaybePromise)\<`TSelectorReturn`\>)

## Returns

[`MapWithArgumentsReturn`](../type-aliases/MapWithArgumentsReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\>
