---
title: "Function: nullSubstitution()"
description: "Function: nullSubstitution() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **nullSubstitution**\<`TSource`, `TDestination`, `TSelectorReturn`\>(`substitution`): [`NullSubstitutionReturn`](../type-aliases/NullSubstitutionReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\>

Defined in: [packages/core/src/lib/member-map-functions/null-substitution.ts:9](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/member-map-functions/null-substitution.ts#L9)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

### TSelectorReturn

`TSelectorReturn` = `unknown`

## Parameters

### substitution

`TSelectorReturn`

## Returns

[`NullSubstitutionReturn`](../type-aliases/NullSubstitutionReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\>
