---
title: "Function: preCondition()"
description: "Function: preCondition() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **preCondition**\<`TSource`, `TDestination`, `TSelectorReturn`\>(`predicate`, `defaultValue?`): [`PreConditionReturn`](../type-aliases/PreConditionReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\>

Defined in: [packages/core/src/lib/member-map-functions/pre-condition.ts:8](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/member-map-functions/pre-condition.ts#L8)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

### TSelectorReturn

`TSelectorReturn` = `unknown`

## Parameters

### predicate

[`ConditionPredicate`](../interfaces/ConditionPredicate)\<`TSource`\>

### defaultValue?

`TSelectorReturn`

## Returns

[`PreConditionReturn`](../type-aliases/PreConditionReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\>
