---
title: "Function: undefinedSubstitution()"
description: "Function: undefinedSubstitution() API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **undefinedSubstitution**\<`TSource`, `TDestination`, `TSelectorReturn`\>(`substitution`): [`UndefinedSubstitutionReturn`](../type-aliases/UndefinedSubstitutionReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\>

Defined in: [packages/core/src/lib/member-map-functions/undefined-substitution.ts:9](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/member-map-functions/undefined-substitution.ts#L9)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

### TSelectorReturn

`TSelectorReturn` = `unknown`

## Parameters

### substitution

`TSelectorReturn`

## Returns

[`UndefinedSubstitutionReturn`](../type-aliases/UndefinedSubstitutionReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\>
