---
title: "Interface: AutoMapOptions"
description: "Interface: AutoMapOptions API reference from @automapper/classes."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/classes**](../index)

***



Defined in: [automap.ts:6](https://github.com/nartc/mapper/blob/main/packages/classes/src/lib/automap.ts#L6)

## Properties

### depth?

> `optional` **depth?**: `number`

Defined in: [automap.ts:14](https://github.com/nartc/mapper/blob/main/packages/classes/src/lib/automap.ts#L14)

Depth for nested models. Default to 1

***

### isGetterOnly?

> `optional` **isGetterOnly?**: `boolean`

Defined in: [automap.ts:18](https://github.com/nartc/mapper/blob/main/packages/classes/src/lib/automap.ts#L18)

Is this property getter-only?

***

### type?

> `optional` **type?**: () => `ClassIdentifier` \| \[`ClassIdentifier`\]

Defined in: [automap.ts:10](https://github.com/nartc/mapper/blob/main/packages/classes/src/lib/automap.ts#L10)

Type Function

#### Returns

`ClassIdentifier` \| \[`ClassIdentifier`\]
