---
title: "Interface: AutoMapperLoggerLike"
description: "Interface: AutoMapperLoggerLike API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



Defined in: [packages/core/src/lib/utils/logger.ts:6](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/utils/logger.ts#L6)

## Properties

### debug?

> `optional` **debug?**: [`AutoMapperLogFn`](../type-aliases/AutoMapperLogFn)

Defined in: [packages/core/src/lib/utils/logger.ts:11](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/utils/logger.ts#L11)

***

### error?

> `optional` **error?**: [`AutoMapperLogFn`](../type-aliases/AutoMapperLogFn)

Defined in: [packages/core/src/lib/utils/logger.ts:10](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/utils/logger.ts#L10)

***

### fatal?

> `optional` **fatal?**: [`AutoMapperLogFn`](../type-aliases/AutoMapperLogFn)

Defined in: [packages/core/src/lib/utils/logger.ts:13](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/utils/logger.ts#L13)

***

### info?

> `optional` **info?**: [`AutoMapperLogFn`](../type-aliases/AutoMapperLogFn)

Defined in: [packages/core/src/lib/utils/logger.ts:8](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/utils/logger.ts#L8)

***

### log?

> `optional` **log?**: [`AutoMapperLogFn`](../type-aliases/AutoMapperLogFn)

Defined in: [packages/core/src/lib/utils/logger.ts:7](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/utils/logger.ts#L7)

***

### trace?

> `optional` **trace?**: [`AutoMapperLogFn`](../type-aliases/AutoMapperLogFn)

Defined in: [packages/core/src/lib/utils/logger.ts:14](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/utils/logger.ts#L14)

***

### verbose?

> `optional` **verbose?**: [`AutoMapperLogFn`](../type-aliases/AutoMapperLogFn)

Defined in: [packages/core/src/lib/utils/logger.ts:12](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/utils/logger.ts#L12)

***

### warn?

> `optional` **warn?**: [`AutoMapperLogFn`](../type-aliases/AutoMapperLogFn)

Defined in: [packages/core/src/lib/utils/logger.ts:9](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/utils/logger.ts#L9)
