---
title: "Interface: CompiledMappingProperty\\<TSource, TDestination\\>"
description: "Interface: CompiledMappingProperty\\<TSource, TDestination\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



Defined in: [packages/core/src/lib/types.ts:549](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L549)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\> = `any`

### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\> = `any`

## Properties

### destinationMemberIdentifier?

> `optional` **destinationMemberIdentifier?**: [`Primitive`](../type-aliases/Primitive) \| `Date` \| [`MetadataIdentifier`](../type-aliases/MetadataIdentifier)\<`any`\>

Defined in: [packages/core/src/lib/types.ts:558](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L558)

***

### destinationMemberPath

> **destinationMemberPath**: `string`[]

Defined in: [packages/core/src/lib/types.ts:553](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L553)

***

### sourceMemberIdentifier?

> `optional` **sourceMemberIdentifier?**: [`Primitive`](../type-aliases/Primitive) \| `Date` \| [`MetadataIdentifier`](../type-aliases/MetadataIdentifier)\<`any`\>

Defined in: [packages/core/src/lib/types.ts:559](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L559)

***

### transformationMapFn

> **transformationMapFn**: [`MemberMapReturn`](../type-aliases/MemberMapReturn)\<`TSource`, `TDestination`\>

Defined in: [packages/core/src/lib/types.ts:554](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L554)

***

### transformationPreConditionDefaultValue?

> `optional` **transformationPreConditionDefaultValue?**: `unknown`

Defined in: [packages/core/src/lib/types.ts:557](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L557)

***

### transformationPreConditionPredicate?

> `optional` **transformationPreConditionPredicate?**: (`source`) => `boolean`

Defined in: [packages/core/src/lib/types.ts:556](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L556)

#### Parameters

##### source

`TSource`

#### Returns

`boolean`

***

### transformationType

> **transformationType**: [`TransformationType`](../enumerations/TransformationType)

Defined in: [packages/core/src/lib/types.ts:555](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L555)
