---
title: "Interface: Converter\\<TSource, TConvertDestination\\>"
description: "Interface: Converter\\<TSource, TConvertDestination\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



Defined in: [packages/core/src/lib/types.ts:111](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L111)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\> = `any`

### TConvertDestination

`TConvertDestination` = `any`

## Methods

### convert()

> **convert**(`source`): `TConvertDestination`

Defined in: [packages/core/src/lib/types.ts:115](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L115)

#### Parameters

##### source

`TSource`

#### Returns

`TConvertDestination`
