---
title: "Interface: MapOptions\\<TSource, TDestination, TExtraArgs\\>"
description: "Interface: MapOptions\\<TSource, TDestination, TExtraArgs\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



Defined in: [packages/core/src/lib/types.ts:128](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L128)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

### TExtraArgs

`TExtraArgs` *extends* `Record`\<`string`, `unknown`\> = `Record`\<`string`, `unknown`\>

## Properties

### afterMap?

> `optional` **afterMap?**: [`MapCallback`](../type-aliases/MapCallback)\<`TSource`, `TDestination`, `TExtraArgs`\>

Defined in: [packages/core/src/lib/types.ts:134](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L134)

***

### beforeMap?

> `optional` **beforeMap?**: [`MapCallback`](../type-aliases/MapCallback)\<`TSource`, `TDestination`, `TExtraArgs`\>

Defined in: [packages/core/src/lib/types.ts:133](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L133)

***

### destinationConstructor?

> `optional` **destinationConstructor?**: [`DestinationConstructor`](../type-aliases/DestinationConstructor)\<`TSource`, `TDestination`\>

Defined in: [packages/core/src/lib/types.ts:135](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L135)

***

### extraArgs?

> `optional` **extraArgs?**: (`mapping`, `destinationObject`) => `TExtraArgs`

Defined in: [packages/core/src/lib/types.ts:136](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L136)

#### Parameters

##### mapping

[`Mapping`](../type-aliases/Mapping)\<`TSource`, `TDestination`\>

##### destinationObject

`TDestination`

#### Returns

`TExtraArgs`
