---
title: "Interface: MappingStrategyInitializerOptions"
description: "Interface: MappingStrategyInitializerOptions API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



Defined in: [packages/core/src/lib/types.ts:736](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L736)

## Properties

### applyMetadata?

> `optional` **applyMetadata?**: [`ApplyMetadata`](../type-aliases/ApplyMetadata)

Defined in: [packages/core/src/lib/types.ts:737](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L737)

***

### destinationConstructor?

> `optional` **destinationConstructor?**: [`DestinationConstructor`](../type-aliases/DestinationConstructor)\<`any`, `any`\>

Defined in: [packages/core/src/lib/types.ts:738](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L738)

## Methods

### postMap()?

> `optional` **postMap**\<`TSource`, `TDestination`\>(`source`, `destination`, `mapping`): `TDestination`

Defined in: [packages/core/src/lib/types.ts:746](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L746)

#### Type Parameters

##### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

##### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

#### Parameters

##### source

`TSource`

##### destination

`TDestination`

##### mapping

[`Mapping`](../type-aliases/Mapping)\<`TSource`, `TDestination`\>

#### Returns

`TDestination`

***

### preMap()?

> `optional` **preMap**\<`TSource`, `TDestination`\>(`source`, `mapping`): `TSource`

Defined in: [packages/core/src/lib/types.ts:739](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L739)

#### Type Parameters

##### TSource

`TSource` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TSource`\>

##### TDestination

`TDestination` *extends* [`Dictionary`](../type-aliases/Dictionary)\<`TDestination`\>

#### Parameters

##### source

`TSource`

##### mapping

[`Mapping`](../type-aliases/Mapping)\<`TSource`, `TDestination`\>

#### Returns

`TSource`
