---
title: "Abstract Class: AutomapperProfile"
description: "Abstract Class: AutomapperProfile API reference from @automapper/nestjs."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/nestjs**](../index)

***



Defined in: [packages/nestjs/src/lib/automapper-profile.ts:8](https://github.com/nartc/mapper/blob/main/packages/nestjs/src/lib/automapper-profile.ts#L8)

## Accessors

### profile

#### Get Signature

> **get** `abstract` **profile**(): `MappingProfile`

Defined in: [packages/nestjs/src/lib/automapper-profile.ts:15](https://github.com/nartc/mapper/blob/main/packages/nestjs/src/lib/automapper-profile.ts#L15)

##### Returns

`MappingProfile`
