---
title: "Variable: DEFAULT\\_MAPPER\\_TOKEN"
description: "Variable: DEFAULT\\_MAPPER\\_TOKEN API reference from @automapper/nestjs."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/nestjs**](../index)

***



> `const` **DEFAULT\_MAPPER\_TOKEN**: `"automapper:nestjs:default"` = `'automapper:nestjs:default'`

Defined in: [packages/nestjs/src/lib/di/get-mapper-token.ts:1](https://github.com/nartc/mapper/blob/main/packages/nestjs/src/lib/di/get-mapper-token.ts#L1)
