---
title: "Enumeration: MappingClassId"
description: "Enumeration: MappingClassId API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



Defined in: [packages/core/src/lib/types.ts:588](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L588)

## Enumeration Members

### callbacks

> **callbacks**: `7`

Defined in: [packages/core/src/lib/types.ts:596](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L596)

***

### compiledPlan

> **compiledPlan**: `9`

Defined in: [packages/core/src/lib/types.ts:598](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L598)

***

### customProperties

> **customProperties**: `3`

Defined in: [packages/core/src/lib/types.ts:592](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L592)

***

### destinationConstructor

> **destinationConstructor**: `5`

Defined in: [packages/core/src/lib/types.ts:594](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L594)

***

### identifierMetadata

> **identifierMetadata**: `1`

Defined in: [packages/core/src/lib/types.ts:590](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L590)

***

### identifiers

> **identifiers**: `0`

Defined in: [packages/core/src/lib/types.ts:589](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L589)

***

### mapper

> **mapper**: `4`

Defined in: [packages/core/src/lib/types.ts:593](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L593)

***

### namingConventions

> **namingConventions**: `8`

Defined in: [packages/core/src/lib/types.ts:597](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L597)

***

### properties

> **properties**: `2`

Defined in: [packages/core/src/lib/types.ts:591](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L591)

***

### typeConverters

> **typeConverters**: `6`

Defined in: [packages/core/src/lib/types.ts:595](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L595)
