---
title: "Enumeration: MappingPropertyClassId"
description: "Enumeration: MappingPropertyClassId API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



Defined in: [packages/core/src/lib/types.ts:503](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L503)

## Enumeration Members

### target

> **target**: `0`

Defined in: [packages/core/src/lib/types.ts:504](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L504)

***

### transformation

> **transformation**: `1`

Defined in: [packages/core/src/lib/types.ts:505](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L505)
