---
title: "Enumeration: NestedMappingPairClassId"
description: "Enumeration: NestedMappingPairClassId API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



Defined in: [packages/core/src/lib/types.ts:532](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L532)

## Enumeration Members

### destination

> **destination**: `0`

Defined in: [packages/core/src/lib/types.ts:533](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L533)

***

### source

> **source**: `1`

Defined in: [packages/core/src/lib/types.ts:534](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L534)
