---
title: "Interface: AutomapperOptionsFactory"
description: "Interface: AutomapperOptionsFactory API reference from @automapper/nestjs."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/nestjs**](../index)

***



Defined in: [packages/nestjs/src/lib/options.ts:17](https://github.com/nartc/mapper/blob/main/packages/nestjs/src/lib/options.ts#L17)

## Methods

### createAutomapperOptions()

> **createAutomapperOptions**(): `CreateMapperOptions` \| `Promise`\<`CreateMapperOptions`\>

Defined in: [packages/nestjs/src/lib/options.ts:18](https://github.com/nartc/mapper/blob/main/packages/nestjs/src/lib/options.ts#L18)

#### Returns

`CreateMapperOptions` \| `Promise`\<`CreateMapperOptions`\>
