---
title: "Function: mikro()"
description: "Function: mikro() API reference from @automapper/mikro."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/mikro**](../index)

***



> **mikro**(`options?`): `MappingStrategyInitializer`\<`MetadataIdentifier`\>

Defined in: [mikro.ts:16](https://github.com/nartc/mapper/blob/main/packages/mikro/src/lib/mikro.ts#L16)

## Parameters

### options?

`MappingStrategyInitializerOptions` = `{}`

## Returns

`MappingStrategyInitializer`\<`MetadataIdentifier`\>
