name: "Feature request"
description: "Suggest an idea for this project"
labels: ["enhancement"]
body:

  - type: textarea
    validations:
      required: false
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is."
      placeholder: "eg: I'm always frustated when ..."

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."

  - type: textarea
    validations:
      required: false
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered so far."

  - type: textarea
    validations:
      required: false
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature you're proposing."
