---
title: "Type Alias: ApplyMetadataFn"
description: "Type Alias: ApplyMetadataFn API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **ApplyMetadataFn** = \<`TModel`\>(`model`, `as`) => `TModel`

Defined in: [packages/core/src/lib/types.ts:678](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L678)

## Type Parameters

### TModel

`TModel` *extends* [`Dictionary`](Dictionary)\<`TModel`\>

## Parameters

### model

[`MetadataIdentifier`](MetadataIdentifier)\<`TModel`\>

### as

[`MetadataObjectMapClassId`](../enumerations/MetadataObjectMapClassId)

## Returns

`TModel`
