---
title: "Type Alias: AutoMapperLogFn"
description: "Type Alias: AutoMapperLogFn API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **AutoMapperLogFn** = (`message`, ...`optionalParams`) => `void`

Defined in: [packages/core/src/lib/utils/logger.ts:1](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/utils/logger.ts#L1)

## Parameters

### message

`unknown`

### optionalParams

...`unknown`[]

## Returns

`void`
