---
title: "Type Alias: Constructor\\<T\\>"
description: "Type Alias: Constructor\\<T\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **Constructor**\<`T`\> = (...`args`) => `T` & [`TransformerMetadataFactory`](../interfaces/TransformerMetadataFactory)

Defined in: [packages/core/src/lib/types.ts:17](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L17)

## Type Parameters

### T

`T` = `any`
