---
title: "Type Alias: ConvertUsingReturn\\<TSource, TDestination, TSelectorReturn\\>"
description: "Type Alias: ConvertUsingReturn\\<TSource, TDestination, TSelectorReturn\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **ConvertUsingReturn**\<`TSource`, `TDestination`, `TSelectorReturn`\> = \[[`ConvertUsing`](../enumerations/TransformationType#convertusing), [`Selector`](Selector)\<`TSource`, `TSelectorReturn`\>\]

Defined in: [packages/core/src/lib/types.ts:435](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L435)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](Dictionary)\<`TDestination`\>

### TSelectorReturn

`TSelectorReturn` = [`SelectorReturn`](SelectorReturn)\<`TDestination`\>
