---
title: "Type Alias: DataMap"
description: "Type Alias: DataMap API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **DataMap** = `Map`\<`symbol`, `number`\>

Defined in: [packages/core/src/lib/types.ts:667](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L667)
