---
title: "Type Alias: FromValueReturn\\<TSource, TDestination, TSelectorReturn\\>"
description: "Type Alias: FromValueReturn\\<TSource, TDestination, TSelectorReturn\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **FromValueReturn**\<`TSource`, `TDestination`, `TSelectorReturn`\> = \[[`FromValue`](../enumerations/TransformationType#fromvalue), () => `TSelectorReturn`\]

Defined in: [packages/core/src/lib/types.ts:429](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L429)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](Dictionary)\<`TDestination`\>

### TSelectorReturn

`TSelectorReturn` = [`SelectorReturn`](SelectorReturn)\<`TDestination`\>
