---
title: "Type Alias: IgnoreReturn\\<TSource, TDestination\\>"
description: "Type Alias: IgnoreReturn\\<TSource, TDestination\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **IgnoreReturn**\<`TSource`, `TDestination`\> = \[[`Ignore`](../enumerations/TransformationType#ignore)\]

Defined in: [packages/core/src/lib/types.ts:462](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L462)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](Dictionary)\<`TDestination`\>
