---
title: "Type Alias: MapCallback\\<TSource, TDestination, TExtraArgs\\>"
description: "Type Alias: MapCallback\\<TSource, TDestination, TExtraArgs\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **MapCallback**\<`TSource`, `TDestination`, `TExtraArgs`\> = (`source`, `destination`, `extraArguments?`) => [`MaybePromise`](MaybePromise)\<`void`\>

Defined in: [packages/core/src/lib/types.ts:118](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L118)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](Dictionary)\<`TDestination`\>

### TExtraArgs

`TExtraArgs` *extends* `Record`\<`string`, `unknown`\> = `Record`\<`string`, `unknown`\>

## Parameters

### source

`TSource`

### destination

`TDestination`

### extraArguments?

`TExtraArgs`

## Returns

[`MaybePromise`](MaybePromise)\<`void`\>
