---
title: "Type Alias: MapDeferReturn\\<TSource, TDestination, TSelectorReturn\\>"
description: "Type Alias: MapDeferReturn\\<TSource, TDestination, TSelectorReturn\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **MapDeferReturn**\<`TSource`, `TDestination`, `TSelectorReturn`\> = \[[`MapDefer`](../enumerations/TransformationType#mapdefer), [`DeferFunction`](../interfaces/DeferFunction)\<`TSource`, `TDestination`, `TSelectorReturn`\>\]

Defined in: [packages/core/src/lib/types.ts:385](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L385)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](Dictionary)\<`TDestination`\>

### TSelectorReturn

`TSelectorReturn` = [`SelectorReturn`](SelectorReturn)\<`TDestination`\>
