---
title: "Type Alias: MapFromReturn\\<TSource, TDestination, TSelectorReturn\\>"
description: "Type Alias: MapFromReturn\\<TSource, TDestination, TSelectorReturn\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **MapFromReturn**\<`TSource`, `TDestination`, `TSelectorReturn`\> = \[[`MapFrom`](../enumerations/TransformationType#mapfrom), [`Selector`](Selector)\<`TSource`, [`MaybePromise`](MaybePromise)\<`TSelectorReturn`\>\>\]

Defined in: [packages/core/src/lib/types.ts:394](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L394)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](Dictionary)\<`TDestination`\>

### TSelectorReturn

`TSelectorReturn` = [`SelectorReturn`](SelectorReturn)\<`TDestination`\>
