---
title: "Type Alias: MappingTransformation\\<TSource, TDestination, TSelectorReturn\\>"
description: "Type Alias: MappingTransformation\\<TSource, TDestination, TSelectorReturn\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **MappingTransformation**\<`TSource`, `TDestination`, `TSelectorReturn`\> = \[[`MemberMapReturn`](MemberMapReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\>, [`PreConditionReturn`](PreConditionReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\>\]

Defined in: [packages/core/src/lib/types.ts:494](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L494)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](Dictionary)\<`TSource`\> = `any`

### TDestination

`TDestination` *extends* [`Dictionary`](Dictionary)\<`TDestination`\> = `any`

### TSelectorReturn

`TSelectorReturn` = [`SelectorReturn`](SelectorReturn)\<`TDestination`\>
