---
title: "Type Alias: Mapping\\<TSource, TDestination\\>"
description: "Type Alias: Mapping\\<TSource, TDestination\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **Mapping**\<`TSource`, `TDestination`\> = \[\[[`MetadataIdentifier`](MetadataIdentifier)\<`TSource`\>, [`MetadataIdentifier`](MetadataIdentifier)\<`TDestination`\>\], \[`TSource`, `TDestination`\], \[`string`[], [`MappingProperty`](MappingProperty)\<`TSource`, `TDestination`, [`SelectorReturn`](SelectorReturn)\<`TDestination`\>\>, \[[`MetadataIdentifier`](MetadataIdentifier) \| [`Primitive`](Primitive) \| `Date`, [`MetadataIdentifier`](MetadataIdentifier) \| [`Primitive`](Primitive) \| `Date`\]\][], \[`string`[], [`MappingProperty`](MappingProperty)\<`TSource`, `TDestination`, [`SelectorReturn`](SelectorReturn)\<`TDestination`\>\>, \[[`MetadataIdentifier`](MetadataIdentifier) \| [`Primitive`](Primitive) \| `Date`, [`MetadataIdentifier`](MetadataIdentifier) \| [`Primitive`](Primitive) \| `Date`\]\][], [`Mapper`](../interfaces/Mapper), [`DestinationConstructor`](DestinationConstructor)\<`TSource`, `TDestination`\>, `Map`\<[`MetadataIdentifier`](MetadataIdentifier) \| [`PrimitiveConstructor`](PrimitiveConstructor) \| `DateConstructor`, \[`Map`\<[`MetadataIdentifier`](MetadataIdentifier) \| [`PrimitiveConstructor`](PrimitiveConstructor) \| `DateConstructor`, \[[`Selector`](Selector)?, [`Selector`](Selector)?\]\>?, `Map`\<[`MetadataIdentifier`](MetadataIdentifier) \| [`PrimitiveConstructor`](PrimitiveConstructor) \| `DateConstructor`, \[[`Selector`](Selector)?, [`Selector`](Selector)?\]\>?\]\>, \[[`MapCallback`](MapCallback)\<`TSource`, `TDestination`\>, [`MapCallback`](MapCallback)\<`TSource`, `TDestination`\>, [`MapCallback`](MapCallback)\<`TSource`[], `TDestination`[]\>, [`MapCallback`](MapCallback)\<`TSource`[], `TDestination`[]\>\], \[[`NamingConvention`](../interfaces/NamingConvention), [`NamingConvention`](../interfaces/NamingConvention)\], [`CompiledMapping`](../interfaces/CompiledMapping)\<`TSource`, `TDestination`\>\]

Defined in: [packages/core/src/lib/types.ts:601](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L601)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](Dictionary)\<`TSource`\> = `any`

### TDestination

`TDestination` *extends* [`Dictionary`](Dictionary)\<`TDestination`\> = `any`
