---
title: "Type Alias: MappingConfiguration\\<TSource, TDestination\\>"
description: "Type Alias: MappingConfiguration\\<TSource, TDestination\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **MappingConfiguration**\<`TSource`, `TDestination`\> = (`mapping`) => `void`

Defined in: [packages/core/src/lib/types.ts:673](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L673)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](Dictionary)\<`TSource`\> = `any`

### TDestination

`TDestination` *extends* [`Dictionary`](Dictionary)\<`TDestination`\> = `any`

## Parameters

### mapping

[`Mapping`](Mapping)\<`TSource`, `TDestination`\>

## Returns

`void`
