---
title: "Type Alias: MapWithArgumentsReturn\\<TSource, TDestination, TSelectorReturn\\>"
description: "Type Alias: MapWithArgumentsReturn\\<TSource, TDestination, TSelectorReturn\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **MapWithArgumentsReturn**\<`TSource`, `TDestination`, `TSelectorReturn`\> = \[[`MapWithArguments`](../enumerations/TransformationType#mapwitharguments), (`source`, `extraArguments`) => [`MaybePromise`](MaybePromise)\<`TSelectorReturn`\>\]

Defined in: [packages/core/src/lib/types.ts:467](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L467)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](Dictionary)\<`TDestination`\>

### TSelectorReturn

`TSelectorReturn` = [`SelectorReturn`](SelectorReturn)\<`TDestination`\>
