---
title: "Type Alias: MapWithReturn\\<TSource, TDestination, TSelectorReturn\\>"
description: "Type Alias: MapWithReturn\\<TSource, TDestination, TSelectorReturn\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **MapWithReturn**\<`TSource`, `TDestination`, `TSelectorReturn`\> = \[[`MapWith`](../enumerations/TransformationType#mapwith), (`sourceObj`, `mapper`, `options?`) => `TSelectorReturn` \| `undefined` \| `null`\]

Defined in: [packages/core/src/lib/types.ts:403](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L403)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](Dictionary)\<`TDestination`\>

### TSelectorReturn

`TSelectorReturn` = [`SelectorReturn`](SelectorReturn)\<`TDestination`\>
