---
title: "Type Alias: MemberMapReturnNoDefer\\<TSource, TDestination, TSelectorReturn\\>"
description: "Type Alias: MemberMapReturnNoDefer\\<TSource, TDestination, TSelectorReturn\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **MemberMapReturnNoDefer**\<`TSource`, `TDestination`, `TSelectorReturn`\> = [`MapInitializeReturn`](MapInitializeReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\> \| [`MapWithReturn`](MapWithReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\> \| [`MapFromReturn`](MapFromReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\> \| [`ConditionReturn`](ConditionReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\> \| [`FromValueReturn`](FromValueReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\> \| [`ConvertUsingReturn`](ConvertUsingReturn)\<`TSource`, `TDestination`\> \| [`NullSubstitutionReturn`](NullSubstitutionReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\> \| [`UndefinedSubstitutionReturn`](UndefinedSubstitutionReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\> \| [`IgnoreReturn`](IgnoreReturn)\<`TSource`, `TDestination`\> \| [`MapWithArgumentsReturn`](MapWithArgumentsReturn)\<`TSource`, `TDestination`, `TSelectorReturn`\>

Defined in: [packages/core/src/lib/types.ts:342](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L342)

## Type Parameters

### TSource

`TSource` *extends* [`Dictionary`](Dictionary)\<`TSource`\>

### TDestination

`TDestination` *extends* [`Dictionary`](Dictionary)\<`TDestination`\>

### TSelectorReturn

`TSelectorReturn` = [`SelectorReturn`](SelectorReturn)\<`TDestination`\>
