---
title: "Type Alias: MetadataIdentifier\\<T\\>"
description: "Type Alias: MetadataIdentifier\\<T\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **MetadataIdentifier**\<`T`\> = `Exclude`\<[`ModelIdentifier`](ModelIdentifier)\<`T`\>, `string`\>

Defined in: [packages/core/src/lib/types.ts:144](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L144)

## Type Parameters

### T

`T` = `any`
