---
title: "Type Alias: NestedMappingPair"
description: "Type Alias: NestedMappingPair API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **NestedMappingPair** = \[[`MetadataIdentifier`](MetadataIdentifier) \| [`Primitive`](Primitive) \| `Date`, [`MetadataIdentifier`](MetadataIdentifier) \| [`Primitive`](Primitive) \| `Date`\]

Defined in: [packages/core/src/lib/types.ts:537](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L537)
