---
title: "Type Alias: Primitive"
description: "Type Alias: Primitive API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **Primitive** = `string` \| `number` \| `boolean` \| `bigint`

Defined in: [packages/core/src/lib/types.ts:27](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L27)
