---
title: "Type Alias: PrimitiveConstructorReturnType\\<TType\\>"
description: "Type Alias: PrimitiveConstructorReturnType\\<TType\\> API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **PrimitiveConstructorReturnType**\<`TType`\> = `TType` *extends* `DateConstructor` \| `Exclude`\<`TType`, [`PrimitiveConstructor`](PrimitiveConstructor)\> ? `InstanceType`\<`TType`\> : `ReturnType`\<`Extract`\<`TType`, [`PrimitiveConstructor`](PrimitiveConstructor)\>\>

Defined in: [packages/core/src/lib/types.ts:41](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L41)

## Type Parameters

### TType

`TType` *extends* [`PrimitiveConstructorExtended`](PrimitiveConstructorExtended)
