---
title: "Type Alias: PrimitiveExtended"
description: "Type Alias: PrimitiveExtended API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



> **PrimitiveExtended** = [`Primitive`](Primitive) \| `Date`

Defined in: [packages/core/src/lib/types.ts:28](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/types.ts#L28)
