---
title: "Class: MappingNotFoundError"
description: "Class: MappingNotFoundError API reference from @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/core**](../index)

***



Defined in: [packages/core/src/lib/errors.ts:16](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/errors.ts#L16)

Thrown when `map()` cannot find a mapping for the given identifiers.

## Extends

- [`AutoMapperError`](AutoMapperError)

## Constructors

### Constructor

> **new MappingNotFoundError**(`sourceName`, `destinationName`): `MappingNotFoundError`

Defined in: [packages/core/src/lib/errors.ts:17](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/errors.ts#L17)

#### Parameters

##### sourceName

`string`

##### destinationName

`string`

#### Returns

`MappingNotFoundError`

#### Overrides

[`AutoMapperError`](AutoMapperError).[`constructor`](AutoMapperError#constructor)

## Properties

### cause?

> `optional` **cause?**: `unknown`

Defined in: node\_modules/.pnpm/typescript@6.0.3/node\_modules/typescript/lib/lib.es2022.error.d.ts:24

#### Inherited from

[`AutoMapperError`](AutoMapperError).[`cause`](AutoMapperError#cause)

***

### destinationName

> `readonly` **destinationName**: `string`

Defined in: [packages/core/src/lib/errors.ts:19](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/errors.ts#L19)

***

### message

> **message**: `string`

Defined in: node\_modules/.pnpm/typescript@6.0.3/node\_modules/typescript/lib/lib.es5.d.ts:1075

#### Inherited from

[`AutoMapperError`](AutoMapperError).[`message`](AutoMapperError#message)

***

### name

> **name**: `string`

Defined in: node\_modules/.pnpm/typescript@6.0.3/node\_modules/typescript/lib/lib.es5.d.ts:1074

#### Inherited from

[`AutoMapperError`](AutoMapperError).[`name`](AutoMapperError#name)

***

### sourceName

> `readonly` **sourceName**: `string`

Defined in: [packages/core/src/lib/errors.ts:18](https://github.com/nartc/mapper/blob/main/packages/core/src/lib/errors.ts#L18)

***

### stack?

> `optional` **stack?**: `string`

Defined in: node\_modules/.pnpm/typescript@6.0.3/node\_modules/typescript/lib/lib.es5.d.ts:1076

#### Inherited from

[`AutoMapperError`](AutoMapperError).[`stack`](AutoMapperError#stack)

***

### stackTraceLimit

> `static` **stackTraceLimit**: `number`

Defined in: node\_modules/.pnpm/@types+node@22.20.0/node\_modules/@types/node/globals.d.ts:68

The `Error.stackTraceLimit` property specifies the number of stack frames
collected by a stack trace (whether generated by `new Error().stack` or
`Error.captureStackTrace(obj)`).

The default value is `10` but may be set to any valid JavaScript number. Changes
will affect any stack trace captured _after_ the value has been changed.

If set to a non-number value, or set to a negative number, stack traces will
not capture any frames.

#### Inherited from

[`AutoMapperError`](AutoMapperError).[`stackTraceLimit`](AutoMapperError#stacktracelimit)

## Methods

### captureStackTrace()

> `static` **captureStackTrace**(`targetObject`, `constructorOpt?`): `void`

Defined in: node\_modules/.pnpm/@types+node@22.20.0/node\_modules/@types/node/globals.d.ts:52

Creates a `.stack` property on `targetObject`, which when accessed returns
a string representing the location in the code at which
`Error.captureStackTrace()` was called.

```js
const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // Similar to `new Error().stack`
```

The first line of the trace will be prefixed with
`${myObject.name}: ${myObject.message}`.

The optional `constructorOpt` argument accepts a function. If given, all frames
above `constructorOpt`, including `constructorOpt`, will be omitted from the
generated stack trace.

The `constructorOpt` argument is useful for hiding implementation
details of error generation from the user. For instance:

```js
function a() {
  b();
}

function b() {
  c();
}

function c() {
  // Create an error without stack trace to avoid calculating the stack trace twice.
  const { stackTraceLimit } = Error;
  Error.stackTraceLimit = 0;
  const error = new Error();
  Error.stackTraceLimit = stackTraceLimit;

  // Capture the stack trace above function b
  Error.captureStackTrace(error, b); // Neither function c, nor b is included in the stack trace
  throw error;
}

a();
```

#### Parameters

##### targetObject

`object`

##### constructorOpt?

`Function`

#### Returns

`void`

#### Inherited from

[`AutoMapperError`](AutoMapperError).[`captureStackTrace`](AutoMapperError#capturestacktrace)

***

### prepareStackTrace()

> `static` **prepareStackTrace**(`err`, `stackTraces`): `any`

Defined in: node\_modules/.pnpm/@types+node@22.20.0/node\_modules/@types/node/globals.d.ts:56

#### Parameters

##### err

`Error`

##### stackTraces

`CallSite`[]

#### Returns

`any`

#### See

https://v8.dev/docs/stack-trace-api#customizing-stack-traces

#### Inherited from

[`AutoMapperError`](AutoMapperError).[`prepareStackTrace`](AutoMapperError#preparestacktrace)
