---
title: "Function: AutoMap()"
description: "Function: AutoMap() API reference from @automapper/classes."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/classes**](../index)

***



## Call Signature

> **AutoMap**(): `PropertyDecorator`

Defined in: [automap.ts:21](https://github.com/nartc/mapper/blob/main/packages/classes/src/lib/automap.ts#L21)

### Returns

`PropertyDecorator`

## Call Signature

> **AutoMap**(`typeFn`): `PropertyDecorator`

Defined in: [automap.ts:22](https://github.com/nartc/mapper/blob/main/packages/classes/src/lib/automap.ts#L22)

### Parameters

#### typeFn

() => `ClassIdentifier` \| \[`ClassIdentifier`\]

### Returns

`PropertyDecorator`

## Call Signature

> **AutoMap**(`options`): `PropertyDecorator`

Defined in: [automap.ts:25](https://github.com/nartc/mapper/blob/main/packages/classes/src/lib/automap.ts#L25)

### Parameters

#### options

[`AutoMapOptions`](../interfaces/AutoMapOptions)

### Returns

`PropertyDecorator`
