---
title: "Function: getMapperToken()"
description: "Function: getMapperToken() API reference from @automapper/nestjs."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/nestjs**](../index)

***



> **getMapperToken**(`name?`): `string`

Defined in: [packages/nestjs/src/lib/di/get-mapper-token.ts:3](https://github.com/nartc/mapper/blob/main/packages/nestjs/src/lib/di/get-mapper-token.ts#L3)

## Parameters

### name?

`string`

## Returns

`string`
