---
title: "Function: InjectMapper()"
description: "Function: InjectMapper() API reference from @automapper/nestjs."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

[**@automapper/nestjs**](../index)

***



> **InjectMapper**(`name?`): `PropertyDecorator` & `ParameterDecorator`

Defined in: [packages/nestjs/src/lib/di/inject-mapper.ts:4](https://github.com/nartc/mapper/blob/main/packages/nestjs/src/lib/di/inject-mapper.ts#L4)

## Parameters

### name?

`string`

## Returns

`PropertyDecorator` & `ParameterDecorator`
