---
title: "@automapper/classes"
description: "Public API reference for @automapper/classes."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

**@automapper/classes**

***



## Interfaces

- [AutoMapOptions](interfaces/AutoMapOptions)

## Variables

- [AUTOMAP\_PROPERTIES\_METADATA\_KEY](variables/AUTOMAP_PROPERTIES_METADATA_KEY)
- [AUTOMAP\_STANDALONE\_METADATA\_KEY](variables/AUTOMAP_STANDALONE_METADATA_KEY)
- [AUTOMAPPER\_METADATA\_FACTORY\_KEY](variables/AUTOMAPPER_METADATA_FACTORY_KEY)

## Functions

- [AutoMap](functions/AutoMap)
- [classes](functions/classes)
- [getMetadataList](functions/getMetadataList)
