---
title: "@automapper/core"
description: "Public API reference for @automapper/core."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

**@automapper/core**

***



## Enumerations

- [MapFnClassId](enumerations/MapFnClassId)
- [MappingCallbacksClassId](enumerations/MappingCallbacksClassId)
- [MappingClassId](enumerations/MappingClassId)
- [MappingPropertiesClassId](enumerations/MappingPropertiesClassId)
- [MappingPropertyClassId](enumerations/MappingPropertyClassId)
- [MappingTransformationClassId](enumerations/MappingTransformationClassId)
- [MetadataClassId](enumerations/MetadataClassId)
- [MetadataObjectMapClassId](enumerations/MetadataObjectMapClassId)
- [NestedMappingPairClassId](enumerations/NestedMappingPairClassId)
- [TransformationType](enumerations/TransformationType)

## Classes

- [AutoMapperError](classes/AutoMapperError)
- [AutoMapperLogger](classes/AutoMapperLogger)
- [CamelCaseNamingConvention](classes/CamelCaseNamingConvention)
- [MapMemberError](classes/MapMemberError)
- [MappingNotFoundError](classes/MappingNotFoundError)
- [PascalCaseNamingConvention](classes/PascalCaseNamingConvention)
- [SnakeCaseNamingConvention](classes/SnakeCaseNamingConvention)

## Interfaces

- [AutoMapperLoggerLike](interfaces/AutoMapperLoggerLike)
- [CompiledMapping](interfaces/CompiledMapping)
- [CompiledMappingDescriptors](interfaces/CompiledMappingDescriptors)
- [CompiledMappingProperty](interfaces/CompiledMappingProperty)
- [ConditionPredicate](interfaces/ConditionPredicate)
- [Converter](interfaces/Converter)
- [CreateMapperOptions](interfaces/CreateMapperOptions)
- [DeferFunction](interfaces/DeferFunction)
- [ErrorHandler](interfaces/ErrorHandler)
- [MapOptions](interfaces/MapOptions)
- [Mapper](interfaces/Mapper)
- [MappingStrategy](interfaces/MappingStrategy)
- [MappingStrategyInitializerOptions](interfaces/MappingStrategyInitializerOptions)
- [NamingConvention](interfaces/NamingConvention)
- [Resolver](interfaces/Resolver)
- [TransformerMetadataFactory](interfaces/TransformerMetadataFactory)

## Type Aliases

- [AbstractConstructor](type-aliases/AbstractConstructor)
- [AnyConstructor](type-aliases/AnyConstructor)
- [ApplyMetadata](type-aliases/ApplyMetadata)
- [ApplyMetadataFn](type-aliases/ApplyMetadataFn)
- [ArrayKeyedMap](type-aliases/ArrayKeyedMap)
- [AutoMapperLogFn](type-aliases/AutoMapperLogFn)
- [ClassIdentifier](type-aliases/ClassIdentifier)
- [CompiledMapStep](type-aliases/CompiledMapStep)
- [ConditionReturn](type-aliases/ConditionReturn)
- [Constructor](type-aliases/Constructor)
- [ConvertUsingReturn](type-aliases/ConvertUsingReturn)
- [DataMap](type-aliases/DataMap)
- [DestinationConstructor](type-aliases/DestinationConstructor)
- [Dictionary](type-aliases/Dictionary)
- [FromValueReturn](type-aliases/FromValueReturn)
- [IgnoreReturn](type-aliases/IgnoreReturn)
- [MapCallback](type-aliases/MapCallback)
- [MapDeferReturn](type-aliases/MapDeferReturn)
- [MapFromReturn](type-aliases/MapFromReturn)
- [MapInitializeReturn](type-aliases/MapInitializeReturn)
- [Mapping](type-aliases/Mapping)
- [MappingConfiguration](type-aliases/MappingConfiguration)
- [MappingProfile](type-aliases/MappingProfile)
- [MappingProperty](type-aliases/MappingProperty)
- [MappingStrategyInitializer](type-aliases/MappingStrategyInitializer)
- [MappingTransformation](type-aliases/MappingTransformation)
- [MapWithArgumentsReturn](type-aliases/MapWithArgumentsReturn)
- [MapWithReturn](type-aliases/MapWithReturn)
- [MaybePromise](type-aliases/MaybePromise)
- [MemberMapReturn](type-aliases/MemberMapReturn)
- [MemberMapReturnNoDefer](type-aliases/MemberMapReturnNoDefer)
- [Metadata](type-aliases/Metadata)
- [MetadataIdentifier](type-aliases/MetadataIdentifier)
- [MetadataList](type-aliases/MetadataList)
- [ModelIdentifier](type-aliases/ModelIdentifier)
- [NamingConventionInput](type-aliases/NamingConventionInput)
- [NestedMappingPair](type-aliases/NestedMappingPair)
- [NullSubstitutionReturn](type-aliases/NullSubstitutionReturn)
- [PathMap](type-aliases/PathMap)
- [PreConditionReturn](type-aliases/PreConditionReturn)
- [Primitive](type-aliases/Primitive)
- [PrimitiveConstructor](type-aliases/PrimitiveConstructor)
- [PrimitiveConstructorExtended](type-aliases/PrimitiveConstructorExtended)
- [PrimitiveConstructorReturnType](type-aliases/PrimitiveConstructorReturnType)
- [PrimitiveExtended](type-aliases/PrimitiveExtended)
- [Selector](type-aliases/Selector)
- [SelectorReturn](type-aliases/SelectorReturn)
- [UndefinedSubstitutionReturn](type-aliases/UndefinedSubstitutionReturn)
- [ValueSelector](type-aliases/ValueSelector)

## Variables

- [defaultStrategyInitializerOptions](variables/defaultStrategyInitializerOptions)

## Functions

- [addProfile](functions/addProfile)
- [afterMap](functions/afterMap)
- [afterMapArray](functions/afterMapArray)
- [autoMap](functions/autoMap)
- [beforeMap](functions/beforeMap)
- [beforeMapArray](functions/beforeMapArray)
- [condition](functions/condition)
- [constructUsing](functions/constructUsing)
- [convertUsing](functions/convertUsing)
- [createMap](functions/createMap)
- [createMapper](functions/createMapper)
- [extend](functions/extend)
- [forMember](functions/forMember)
- [forSelf](functions/forSelf)
- [fromValue](functions/fromValue)
- [getRecursiveValue](functions/getRecursiveValue)
- [ignore](functions/ignore)
- [isDateConstructor](functions/isDateConstructor)
- [isEmpty](functions/isEmpty)
- [isMappableIdentifier](functions/isMappableIdentifier)
- [isPrimitiveConstructor](functions/isPrimitiveConstructor)
- [mapDefer](functions/mapDefer)
- [mapFrom](functions/mapFrom)
- [mapWith](functions/mapWith)
- [mapWithArguments](functions/mapWithArguments)
- [namingConventions](functions/namingConventions)
- [nullSubstitution](functions/nullSubstitution)
- [preCondition](functions/preCondition)
- [set](functions/set)
- [setMutate](functions/setMutate)
- [setRecursiveValue](functions/setRecursiveValue)
- [typeConverter](functions/typeConverter)
- [undefinedSubstitution](functions/undefinedSubstitution)
