---
title: "@automapper/mikro"
description: "Public API reference for @automapper/mikro."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

**@automapper/mikro**

***



## Functions

- [mikro](functions/mikro)
