---
title: "@automapper/nestjs"
description: "Public API reference for @automapper/nestjs."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

**@automapper/nestjs**

***



## Classes

- [AutomapperModule](classes/AutomapperModule)
- [AutomapperProfile](classes/AutomapperProfile)

## Interfaces

- [AutomapperAsyncOptions](interfaces/AutomapperAsyncOptions)
- [AutomapperGlobalOptions](interfaces/AutomapperGlobalOptions)
- [AutomapperOptionsFactory](interfaces/AutomapperOptionsFactory)

## Type Aliases

- [AutomapperOptions](type-aliases/AutomapperOptions)

## Variables

- [DEFAULT\_MAPPER\_TOKEN](variables/DEFAULT_MAPPER_TOKEN)
- [MapInterceptor](variables/MapInterceptor)
- [MapPipe](variables/MapPipe)

## Functions

- [getMapperToken](functions/getMapperToken)
- [InjectMapper](functions/InjectMapper)
