---
title: "@automapper/pojos"
description: "Public API reference for @automapper/pojos."
---

<!-- Generated by scripts/generate-api.mjs. Do not edit. -->

**@automapper/pojos**

***



## Classes

- [PojosMetadataMap](classes/PojosMetadataMap)

## Type Aliases

- [PojoMetadata](type-aliases/PojoMetadata)

## Functions

- [pojos](functions/pojos)
