# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Test
on:
  # Allow triggering this workflow manually via GitHub CLI/web
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - '**.ts'
      - '**.js'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
  pull_request:
    branches: [ main ]
    paths:
      - '**.ts'
      - '**.js'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'

jobs:
  jest:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test:all
